name: Docker Image CI

on:
  push:
    branches: [ main ]
    
jobs:

  build:

    runs-on: docker

    steps:
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag  --tag pyramid
